### ISSUE TITLE
Story (part two)

### ISSUE THREAD

**Issue by LordoftheWild** [LordoftheWild/the-wild#7]
**SOLVED**

**Comment by Bergenfrundt** [comment]
how do you want to make this game? 

you could make it alert based like me and ryan's game [here](http://Loquacious.github.io/arsh-sim)

**Comment by LordoftheWild** [comment]
NO!

**Comment by LordoftheWild** [comment]
GRAPHICS!

**Comment by LordoftheWild** [comment]
and arshneet simulator was cool

**Comment by Bergenfrundt** [comment]
k stop being so fucking demanding you aren't getting anywhere like that

also making a game like that could take years for someone who doesn't know how to code

hell, you don't even know what language you're gonna write it in
